### ISSUE TITLE
abd support

### ISSUE THREAD

**Issue by aruelo** [Kusumoto/docker-ionic-android-sdk#17]
Hi, thanks for the Dockerfile and image. It would be helpfull to have installed abd for testing android devices (Android Debug Bridge). Just a sugestion, thanks.

**Comment by Kusumoto** [comment]
Hi  @aruelo 

Thank you for suggestion. I will try to find solution for this.

**Comment by aruelo** [comment]
Hey, i found the way to use the adb with your image:

docker run --privileged -v /dev/bus/usb:/dev/bus/usb -P -v $(pwd):/ionicapp kusumoto/docker-ionic-android-sdk /opt/android-sdk/platform-tools/adb devices

Sorry for opening the issue! 
And thanks for your time!

**Comment by Kusumoto** [comment]
Awesome!

I will update README file for this instruction.

Thank you very much for information.
